// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Kretu {
    
    
    public partial class MainWindow {
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Kretu.MainWindow
            this.Name = "Kretu.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("MainWindow");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "stock_weather-sunny", Gtk.IconSize.Menu, 16);
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        }
    }
}
